ld:
  host: 127.0.0.1
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
#nacos
nacos:
  #dev
  namespace: 79622650-2ad0-4651-945e-82929157836f
#database
DB_HOST: ${ld.host}:${ld.mysql-port}
DB_NAME: bld
DB_USERNAME: root
DB_PASSWORD: qqq111
REDIS_PASSWORD: ENC(dt7eo1i+3pVrhVI+cJicCa0AsP1mhq9wbwRJ7vOAt+TQtbLZr1Sq+oSLHmmLosz3)